### ISSUE TITLE
Reuse buffers in `bufio.Scanner`s

### ISSUE THREAD

**Issue by sinkingpoint** [leodido/go-syslog#16]
At the moment, every parser (one of which is constructed for each message), allocates a new buffer (https://github.com/leodido/go-syslog/blob/develop/octetcounting/scanner.go#L42). In high throughput scenarios, this can chew up a huge amount of CPU allocating memory to parse messages. I would like to propose that we create a new `sync.Pool` that stores `bufio.Reader`s which https://github.com/leodido/go-syslog/blob/develop/octetcounting/scanner.go#L40 can pull from, rather than allocating a new buffer every time.

**Comment by sinkingpoint** [comment]
As a demonstrative, we were chewing 70 cores using go-syslog through the OpenTelemetry Collector, which reduced to 3 when introducing a sync.Pool to store/reuse `bufio.Reader`s

<img width="1628" alt="image" src="https://github.com/leodido/go-syslog/assets/4386405/8634b1cf-a694-4173-9ca0-4e83160d4228">

pprof:

<img width="162" alt="image" src="https://github.com/leodido/go-syslog/assets/4386405/93976ea4-0f01-4bb9-bb8e-d38e36a98fbf">

**Comment by leodido** [comment]
I love the analysis @sinkingpoint (ty!). Also, I like the idea of a pool for buffers.

Would love to get a PR and review it!

**Comment by sinkingpoint** [comment]
Sure: https://github.com/leodido/go-syslog/pull/18
